[build-system]
build-backend = "enscons.api"
requires = ["pytoml>=0.1", "enscons>=0.23", "PySide6"]

[tool.enscons]
author = "oczkoisse"
author_email = "oczkoisse@pm.me"
classifiers = [
  "Programming Language :: Python :: 3",
]
description = "Tool for annotating videos"
dependencies = [
  "PySide6",
  "PyOpenGL",
  "PyOpenGL-accelerate",
  "av",
  "numpy"
]
license = "LGPL"
name = "numbat"
packages = ["numbat"]
src_root = "src"
url = "https://github.com/oczkoisse/numbat"
version = "0.0.1"

[tool.enscons.optional-dependencies]
test = [
  "pytest >= 6.0", # Remember to change tool.pytest.ini_options.minversion
  "pytest-qt",
  "tox >= 3.24.1", # Remember to change tox.minversion
]

[tool.enscons.entry_points]
console_scripts = ["numbat = numbat.MainWindow:main"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
  "tests"
]

[tool.tox]
legacy_tox_ini = """
[tox]
# support for backends not implementing optional hooks
minversion = 3.24.1
envlist = py37, py38, py39
isolated_build = true

[testenv]
deps =
    pytest >= 6.0 # for pytest settings in pyproject.toml
    pytest-qt
commands = pytest {posargs}
"""

[tool.interrogate]
fail-under = 95
exclude = [
  "setup.py",
  "src/*_ui.py",  # Ignore .py files auto-generated from .ui files
  "src/*_rc.py",  # Ignore .py files auto-generated from .qrc files
  "tests/*.py",   # Ignore tests
]

[tool.pydocstyle]
convention = "google"
# Don't match any .py file starting with
# - setup    setup.py
# - test_    test files
# Don't match any .py files ending with
# - _ui      auto-generated from .ui files
# - _rc      auto-generated from .qrc files
match = '(?!(setup|test_)).+(?<!(_ui|_rc))\.py'
match_dir = 'src'

[tool.isort]
profile = "black"
skip_gitignore = true
atomic = true
